Add countrySelect component
mittwald/flow pull request #1043
Opened 2024-12-05 10:51 UTC by JLampeMW

2024-12-05 12:06 UTC, Lisa18289 commented on packages/components/src/components/CountrySelect/CountrySelect.tsx
> +  extends PropsWithChildren<
du kannst auch einfach mit den SelectProps extenden

2024-12-05 12:07 UTC, Lisa18289 commented on packages/components/src/components/CountrySelect/CountrySelect.tsx
> +  defaultCountry?: string;
das kann eigentlich weg, gibt ja schon das property defaultSelectedKey

2024-12-05 12:08 UTC, Lisa18289 commented on packages/components/src/components/CountrySelect/CountrySelect.tsx
> +  onCountryChange?: (countryCode: string) => void;
hier gibts auch schon onSelectionChange

2024-12-05 12:12 UTC, Lisa18289 commented on packages/components/src/components/CountrySelect/components/CountryList.ts
> +export const CountryList: Record<string, string> = {
hier bräuchten wir noch eine Alternative mit englischen namen, du kannst zb in der AlertIcon Component gucken, wie die Übersetzungen da gebaut sind

2024-12-05 12:13 UTC, Lisa18289 commented
In den Docs müsste dann auch noch ein entsprechender Abschnitt zur CountrySelect Component eingebaut werden

2024-12-06 10:14 UTC, mfal requested changes

2024-12-06 10:14 UTC, mfal commented on packages/components/src/components/CountrySelect/CountrySelect.tsx
> +export const CountrySelect = flowComponent(
Maybe it is sufficient to just provide a `<CountryOptions />` component, that comes with it's own properties like `sortBy` (the compare functions), or `filterBy`.

2024-12-06 10:14 UTC, mfal commented on packages/components/src/components/CountrySelect/CountrySelect.tsx
> +    });
Sorting result should be `memoized`

2024-12-10 11:42 UTC, mfal approved these changes

2024-12-10 11:43 UTC, merged