Update docs styling
mittwald/flow pull request #185
Opened 2024-02-22 10:33 UTC by Lisa18289

2024-02-26 12:42 UTC, darioed commented on packages/docs/src/app/_components/layout/HeaderNavigation/HeaderNavigation.module.scss
> +  flex-direction: row;
```suggestion
  flex-direction: row;
  gap: var(--navigation--item-to-item-spacing)
```
Bei mir wird sonst die outline des buttons beim hover abgeschnitten, wenn ich auf "Components" bin und über "Getting started" hover

2024-02-26 12:46 UTC, Lisa18289 commented on packages/docs/src/app/_components/layout/HeaderNavigation/HeaderNavigation.module.scss
> +  flex-direction: row;
das wird oben eh nochmal ne andere Navigation, das ist nur vorübergehend und wird dann richtig gestyled wenn da die richtige Navigation drin ist

2024-02-26 13:35 UTC, mfal requested changes

2024-02-27 07:44 UTC, Lisa18289 commented on packages/docs/src/app/_components/layout/HeaderNavigation/HeaderNavigation.tsx
> +  };
Auslagern ging nicht, da bekomm ich Fehler, aber ich habs ein bisschen anders gebaut, vlt ist das auch ok^^

![Bildschirmfoto 2024-02-27 um 07 32 05](https://github.com/mittwald/flow/assets/84317589/bc5d39b7-15a8-4d30-970b-f14e5837cb95)

2024-02-29 08:03 UTC, mfal requested changes

2024-02-29 08:03 UTC, mfal commented on packages/docs/src/app/layout.module.scss
> +  }
Kannst du hier die Verschachtelung rausnehmen?

2024-02-29 08:03 UTC, mfal commented on packages/docs/src/app/layout.module.scss
> +  .header .heading {
```suggestion
.heading {
```

2024-02-29 08:03 UTC, mfal commented on packages/docs/src/app/layout.tsx
> +          <div className={styles.headerContent}>
Wenn ich das richtig sehe, nutzt du die Verachachetlung für den Hitnergrund? Kannst du das mit einem absolut positionierten `:after` lösen?

Siehe https://stackoverflow.com/a/29881959

2024-02-29 08:27 UTC, mfal approved these changes

2024-02-29 08:30 UTC, merged