Add switch and badge to section header
mittwald/flow pull request #198
Opened 2024-02-29 12:41 UTC by Lisa18289

2024-03-15 09:20 UTC, mfal commented on packages/components/src/components/Section/Section.module.scss
> +      align-self: flex-end;
Wieso nutzt du hier jetzt globale Klassennamen?

2024-03-18 16:20 UTC, mfal requested changes

2024-03-18 16:20 UTC, mfal commented on packages/components/src/components/propTypes/index.ts
Wenn du hier sämtliche Components Type-mäßig ergänzt, sollten diese in der Render-Methode auch `useProps` verwenden. Ich hätte gesagt, wir machen das nur, wenn wir es wirklich brauchen.

2024-03-19 06:21 UTC, Lisa18289 commented on packages/components/src/components/propTypes/index.ts
aber ich hab ja nur die verwendet die ich wirklich brauche 🤔 ich hab das hier nur einmal alphabetisch sortiert, deswegen die vielen changes, aber ich habs jetzt auch nochmal durchgeschaut, bei allen außer navigation wird useProps verwendet, navigation wird bisher aber auch nicht gebraucht die hab ich da jetzt raus genommen

2024-03-19 07:19 UTC, mfal approved these changes

2024-03-19 07:20 UTC, merged